### ISSUE TITLE
Implement IPv6 Support

### ISSUE THREAD

**Issue by mtthwjrgnsn** [mtthwjrgnsn/ip_push#1]
From https://github.com/p2j/ip_tweet/issues/1:

> wtfismyip.com will give both IPv4 and IPv6 address, but this tool doesn't handle that yet. Fix it.

---

- IPv4 addresses: `ipv4.wtfismyip.com/text`
- IPv6 addresses: `ipv6.wtfismyip.com/text`
  
I've noticed if you don't have an IPv6 connection you can't connect to `ipv6.wtfismyip.com`, that can be useful...

**Comment by mtthwjrgnsn** [comment]
Previous comments from previous hosted location:

> I added basic capabilities.
>
>Might be useful to allow either IP to be changed and updated independently.
Perhaps checking for both IPv4 and IPv6 within a minute also breaks the rate-limiting request.

---

> Things to do:
>
> - [x] Check if this doesn't break things when IPv6 is not allowed.
> - [ ] Test independent checking

---

> We blow up when we can't connect to an IPv6 address.
> 
> ```
> [2018-08-03 16:50:26,994] - __main__ - INFO - IPv4 capabilities are True
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
>     self.send(msg)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
>     self.connect()
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1392, in connect
>     super().connect()
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 704, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 8] nodename nor servname provided, or not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "ippush.py", line 139, in <module>
>     IPPush().do_update()
>   File "ippush.py", line 123, in do_update
>     self.get_current_ip()
>   File "ippush.py", line 63, in get_current_ip
>     with urllib.request.urlopen('https://ipv6.wtfismyip.com/text') as r:
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
>     response = self._open(req, data)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
>     '_open', req)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known
> ```

---

> TODO:
> 
> * [ ] If we don't have IPv6 capabilities, don't show blank address in the push.
> 
> Under each scenario the message should be similar:
> 
> * IPv4 Only:
>   
> ```
> ippush-dev: 
> Sat Aug  4 11:46:14 2018
> 
> 
> IPv4:
> New external IP for dev is
>     127.0.0.1
> Old IP was:
>     0.0.0.0
> ```
> 
> * IPv4 and IPv6:
> 
> ```
> ippush-dev: 
> Sat Aug  4 11:46:14 2018
> 
> 
> IPv4:
> New external IP for dev is
>     127.0.0.1
> Old IP was:
>     0.0.0.0
> 
> IPv6:
> New external IPv6 address is:
>     
> Old IPv6 address was:
>     ::
> ```
> 
> * IPv6 Only:
> 
> ```
> ippush-dev: 
> Sat Aug  4 11:46:14 2018
> 
> 
> IPv6:
> New external IPv6 address is:
>     
> Old IPv6 address was:
>     ::
> ```
> 
> *I'm not sure I'll ever only have an IPv6 address, but the use case might fit someone else's.*

**Comment by mtthwjrgnsn** [comment]
This is rather hard to test on an IPv4-only internet connection.
